# Generated by Django 2.2 on 2019-11-30 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=32)),
                ('c_password', models.CharField(default='', max_length=32)),
                ('c_email', models.EmailField(max_length=254, unique=True)),
                ('c_phone', models.IntegerField(max_length=10, unique=True)),
                ('company', models.CharField(max_length=64)),
                ('income', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=32)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.IntegerField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('e_name', models.CharField(max_length=32)),
                ('e_email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('e_phone', models.IntegerField(max_length=10, unique=True)),
                ('job_title', models.CharField(choices=[('DBA', 'Database_Administrator'), ('Sales', 'Salesperson')], max_length=16)),
                ('e_password', models.CharField(default='', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('o_id', models.AutoField(primary_key=True, serialize=False)),
                ('o_status', models.CharField(choices=[('P', 'Process'), ('S', 'Shipping'), ('D', 'Delivered')], max_length=16)),
                ('o_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.FloatField(default=10.0)),
                ('p_name', models.CharField(max_length=32)),
                ('quantity', models.IntegerField(default=500)),
                ('p_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Resolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution_name', models.CharField(choices=[('C', 'Change'), ('R', 'Return'), ('A', 'Add')], max_length=10)),
                ('step', models.CharField(choices=[('P', 'Pending'), ('AD', 'Approve')], max_length=10)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project.Customer')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project.Employee')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project.OrderHistory')),
            ],
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Product'),
        ),
        migrations.CreateModel(
            name='EmployeeAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=32)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.IntegerField(max_length=5)),
                ('e_address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project.Employee')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='c_address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project.CustomerAddress'),
        ),
        migrations.AddField(
            model_name='customer',
            name='order_history',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.OrderHistory'),
        ),
        migrations.AddField(
            model_name='customer',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Product'),
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('ca_id', models.AutoField(primary_key=True, serialize=False)),
                ('summary', models.CharField(max_length=128)),
                ('ca_description', models.TextField(default='the product was damaged after washed.')),
                ('ca_time', models.DateTimeField()),
                ('ca_status', models.CharField(choices=[('O', 'Open'), ('C', 'Close')], max_length=10)),
                ('comment', models.TextField(default='We are so sorry for hearing that.')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project.Customer')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project.Employee')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Product')),
            ],
        ),
    ]
